-- ==============================================================================
-- Sawtio — مخطط قاعدة البيانات الشامل (Full Supabase Schema)
-- شغل هذا الملف بالكامل في Supabase SQL Editor لتهيئة المشروع من الصفر
-- ==============================================================================

create extension if not exists pgcrypto;

-- 1. جدول الملفات الشخصية للمستخدمين (Profiles)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'عضو Sawtio',
  handle text,
  avatar_url text,
  role text default 'member' check (role in ('member', 'admin', 'moderator')),
  level int default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. جدول الغرف الصوتية (Rooms)
create table if not exists public.rooms (
  id text primary key default gen_random_uuid()::text,
  slug text unique not null,
  host_id uuid references auth.users(id) on delete set null,
  title text not null check (char_length(trim(title)) between 2 and 200),
  topic text not null default 'مجتمع',
  description text default '',
  cover_color text default '#ff7a68',
  status text not null default 'live' check (status in ('live', 'active', 'ended', 'scheduled')),
  max_speakers int not null default 10,
  listener_count int not null default 1,
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

-- 3. جدول رسائل الغرف العامة (Room Messages)
create table if not exists public.room_messages (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  message_type text default 'text',
  created_at timestamptz not null default now()
);

-- 4. المحادثات المباشرة الخاصة (Direct Conversations)
create table if not exists public.direct_conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5. أعضاء المحادثات الخاصة (Conversation Members)
create table if not exists public.direct_conversation_members (
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

-- 6. الرسائل الخاصة (Direct Messages)
create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now()
);

-- الفهارس لتسريع البحث والاستعلام
create index if not exists rooms_created_at_idx on public.rooms (created_at desc);
create index if not exists rooms_status_idx on public.rooms (status);
create index if not exists room_messages_room_idx on public.room_messages (room_id, created_at desc);
create index if not exists direct_members_user_idx on public.direct_conversation_members (user_id);
create index if not exists direct_messages_idx on public.direct_messages (conversation_id, created_at);

-- دالة للتحقق من العضوية بالمحادثة
create or replace function public.is_direct_conversation_member(
  target_conversation_id uuid,
  target_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.direct_conversation_members
    where conversation_id = target_conversation_id
      and user_id = target_user_id
  );
$$;

-- تفعيل أمان مستوى الصفوف (Row Level Security)
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.room_messages enable row level security;
alter table public.direct_conversations enable row level security;
alter table public.direct_conversation_members enable row level security;
alter table public.direct_messages enable row level security;

-- صلاحيات عامة (Profiles & Rooms للجميع قراءة، وللمسجلين تعديل)
create policy "Allow public read profiles" on public.profiles for select using (true);
create policy "Allow users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Allow users insert own profile" on public.profiles for insert with check (auth.uid() = id);

create policy "Allow public read rooms" on public.rooms for select using (true);
create policy "Allow auth users create rooms" on public.rooms for insert to authenticated with check (auth.uid() = host_id);
create policy "Allow host update room" on public.rooms for update to authenticated using (auth.uid() = host_id) with check (auth.uid() = host_id);

create policy "Allow public read room messages" on public.room_messages for select using (true);
create policy "Allow auth users send room messages" on public.room_messages for insert with check (auth.role() = 'authenticated');

-- سياسات الرسائل الخاصة
create policy "direct members can read conversations" on public.direct_conversations for select using (public.is_direct_conversation_member(id, auth.uid()));
create policy "authenticated users can create conversations" on public.direct_conversations for insert with check (true);
create policy "direct members can read membership" on public.direct_conversation_members for select using (public.is_direct_conversation_member(conversation_id, auth.uid()));
create policy "authenticated users can join conversations" on public.direct_conversation_members for insert with check (user_id = auth.uid() or public.is_direct_conversation_member(conversation_id, auth.uid()));
create policy "direct members can read direct messages" on public.direct_messages for select using (public.is_direct_conversation_member(conversation_id, auth.uid()));
create policy "direct members can send direct messages" on public.direct_messages for insert with check (sender_id = auth.uid() and public.is_direct_conversation_member(conversation_id, auth.uid()));

-- 7. جدول معاملات الهدايا الافتراضية (Gift Transactions)
create table if not exists public.gift_transactions (
  id bigint generated by default as identity primary key,
  gift_id text not null,
  gift_name text not null,
  coins int not null,
  sender_name text not null,
  recipient_name text not null,
  room_id text references public.rooms(id) on delete set null,
  message text,
  created_at timestamptz not null default now()
);

alter table public.gift_transactions enable row level security;
create policy "Allow public read gift transactions" on public.gift_transactions for select using (true);
create policy "Allow auth insert gift transactions" on public.gift_transactions for insert with check (true);

-- تفعيل التحديثات اللحظية (Realtime)
do $$
begin
  alter publication supabase_realtime add table public.rooms;
  alter publication supabase_realtime add table public.room_messages;
  alter publication supabase_realtime add table public.direct_messages;
  alter publication supabase_realtime add table public.gift_transactions;
exception when duplicate_object then null;
end $$;

-- لا تُدرج بيانات تجريبية هنا. الغرف تُنشأ من التطبيق بعد تسجيل الدخول
-- وتُحفظ في public.rooms مع ربطها بالمستخدم الحقيقي عبر host_id.
