-- Sawtio additive migration for the existing Supabase schema.
-- The project already has: rooms, room_participants, room_messages,
-- profiles, wallets, wallet_transactions, gifts and gift_inventory.
-- This file does NOT alter or recreate those tables.
-- Run it once in Supabase SQL Editor to add private direct messaging only.

create extension if not exists pgcrypto;

create table if not exists public.direct_conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.direct_conversation_members (
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists direct_members_user_idx
  on public.direct_conversation_members (user_id);
create index if not exists direct_messages_conversation_created_idx
  on public.direct_messages (conversation_id, created_at);

-- SECURITY DEFINER avoids recursive RLS evaluation when a policy checks membership.
create or replace function public.is_direct_conversation_member(
  target_conversation_id uuid,
  target_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.direct_conversation_members
    where conversation_id = target_conversation_id
      and user_id = target_user_id
  );
$$;

revoke all on function public.is_direct_conversation_member(uuid, uuid) from public;
grant execute on function public.is_direct_conversation_member(uuid, uuid) to authenticated;

alter table public.direct_conversations enable row level security;
alter table public.direct_conversation_members enable row level security;
alter table public.direct_messages enable row level security;

grant select, insert, update on public.direct_conversations to authenticated;
grant select, insert on public.direct_conversation_members to authenticated;
grant select, insert on public.direct_messages to authenticated;

drop policy if exists "direct members can read conversations" on public.direct_conversations;
create policy "direct members can read conversations"
on public.direct_conversations for select
to authenticated
using (public.is_direct_conversation_member(id, auth.uid()));

drop policy if exists "authenticated users can create conversations" on public.direct_conversations;
create policy "authenticated users can create conversations"
on public.direct_conversations for insert
to authenticated
with check (true);

drop policy if exists "direct members can update conversations" on public.direct_conversations;
create policy "direct members can update conversations"
on public.direct_conversations for update
to authenticated
using (public.is_direct_conversation_member(id, auth.uid()))
with check (public.is_direct_conversation_member(id, auth.uid()));

drop policy if exists "direct members can read membership" on public.direct_conversation_members;
create policy "direct members can read membership"
on public.direct_conversation_members for select
to authenticated
using (public.is_direct_conversation_member(conversation_id, auth.uid()));

drop policy if exists "authenticated users can join direct conversations" on public.direct_conversation_members;
create policy "authenticated users can join direct conversations"
on public.direct_conversation_members for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.is_direct_conversation_member(conversation_id, auth.uid())
);

drop policy if exists "direct members can read messages" on public.direct_messages;
create policy "direct members can read messages"
on public.direct_messages for select
to authenticated
using (public.is_direct_conversation_member(conversation_id, auth.uid()));

drop policy if exists "direct members can send messages" on public.direct_messages;
create policy "direct members can send messages"
on public.direct_messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and public.is_direct_conversation_member(conversation_id, auth.uid())
);

-- Existing room messages and the new direct messages can be subscribed to in Realtime.
do $$
begin
  alter publication supabase_realtime add table public.room_messages;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.direct_messages;
exception when duplicate_object then null;
end $$;

-- 5) Admin-only monitoring policies.
-- The existing profiles table already contains a role column.
create or replace function public.is_admin(target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = target_user_id and role = 'admin'
  );
$$;

revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to authenticated;

drop policy if exists "admins can read all profiles" on public.profiles;
create policy "admins can read all profiles"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists "admins can read all rooms" on public.rooms;
create policy "admins can read all rooms"
on public.rooms for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "admins can read all room messages" on public.room_messages;
create policy "admins can read all room messages"
on public.room_messages for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "admins can read all direct conversations" on public.direct_conversations;
create policy "admins can read all direct conversations"
on public.direct_conversations for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "admins can read all direct membership" on public.direct_conversation_members;
create policy "admins can read all direct membership"
on public.direct_conversation_members for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "admins can read all direct messages" on public.direct_messages;
create policy "admins can read all direct messages"
on public.direct_messages for select
to authenticated
using (public.is_admin(auth.uid()));
