-- Sawtio production schema: rooms, profiles, private messages and Realtime.
-- Run this whole file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  host_user_id uuid references auth.users(id) on delete set null,
  title text not null,
  topic text not null default 'مجتمع',
  category text not null default 'الأكثر نشاطًا',
  listeners integer not null default 1 check (listeners >= 0),
  status text not null default 'مباشر الآن',
  accent text not null default 'coral' check (accent in ('coral', 'teal', 'violet', 'amber')),
  host text not null,
  host_initials text not null,
  host_tone text not null default 'tone-coral',
  private boolean not null default false,
  members jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.rooms add column if not exists host_user_id uuid references auth.users(id) on delete set null;
alter table public.rooms add column if not exists title text;
alter table public.rooms add column if not exists topic text default 'مجتمع';
alter table public.rooms add column if not exists category text default 'الأكثر نشاطًا';
alter table public.rooms add column if not exists listeners integer default 1;
alter table public.rooms add column if not exists status text default 'مباشر الآن';
alter table public.rooms add column if not exists accent text default 'coral';
alter table public.rooms add column if not exists host text;
alter table public.rooms add column if not exists host_initials text;
alter table public.rooms add column if not exists host_tone text default 'tone-coral';
alter table public.rooms add column if not exists private boolean default false;
alter table public.rooms add column if not exists members jsonb default '[]'::jsonb;
alter table public.rooms add column if not exists created_at timestamptz default now();

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'عضو جديد',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists rooms_created_at_idx on public.rooms (created_at desc);
create index if not exists rooms_host_user_idx on public.rooms (host_user_id);
create index if not exists conversation_members_user_idx on public.conversation_members (user_id);
create index if not exists messages_conversation_created_idx on public.messages (conversation_id, created_at);

alter table public.rooms enable row level security;
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

grant select on table public.rooms to anon, authenticated;
grant insert, update on table public.rooms to authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update on table public.conversations to authenticated;
grant select, insert on table public.conversation_members to authenticated;
grant select, insert on table public.messages to authenticated;

drop policy if exists "public can read rooms" on public.rooms;
create policy "public can read rooms" on public.rooms for select to anon, authenticated using (private = false or host_user_id = auth.uid());
drop policy if exists "public can create rooms" on public.rooms;
drop policy if exists "authenticated users can create rooms" on public.rooms;
create policy "authenticated users can create rooms" on public.rooms for insert to authenticated with check (host_user_id = auth.uid());
drop policy if exists "hosts can update rooms" on public.rooms;
create policy "hosts can update rooms" on public.rooms for update to authenticated using (host_user_id = auth.uid()) with check (host_user_id = auth.uid());

drop policy if exists "members can read profiles" on public.profiles;
create policy "members can read profiles" on public.profiles for select to authenticated using (true);
drop policy if exists "users can create own profile" on public.profiles;
create policy "users can create own profile" on public.profiles for insert to authenticated with check (id = auth.uid());
drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "members can read conversations" on public.conversations;
create policy "members can read conversations" on public.conversations for select to authenticated using (exists (select 1 from public.conversation_members cm where cm.conversation_id = id and cm.user_id = auth.uid()));
drop policy if exists "users can create conversations" on public.conversations;
create policy "users can create conversations" on public.conversations for insert to authenticated with check (true);
drop policy if exists "members can update conversations" on public.conversations;
create policy "members can update conversations" on public.conversations for update to authenticated using (exists (select 1 from public.conversation_members cm where cm.conversation_id = id and cm.user_id = auth.uid()));

drop policy if exists "members can read conversation members" on public.conversation_members;
create policy "members can read conversation members" on public.conversation_members for select to authenticated using (exists (select 1 from public.conversation_members cm where cm.conversation_id = conversation_id and cm.user_id = auth.uid()));
drop policy if exists "users can join conversations" on public.conversation_members;
create policy "users can join conversations" on public.conversation_members for insert to authenticated with check (user_id = auth.uid() or exists (select 1 from public.conversation_members cm where cm.conversation_id = conversation_id and cm.user_id = auth.uid()));

drop policy if exists "members can read messages" on public.messages;
create policy "members can read messages" on public.messages for select to authenticated using (exists (select 1 from public.conversation_members cm where cm.conversation_id = messages.conversation_id and cm.user_id = auth.uid()));
drop policy if exists "members can send messages" on public.messages;
create policy "members can send messages" on public.messages for insert to authenticated with check (sender_id = auth.uid() and exists (select 1 from public.conversation_members cm where cm.conversation_id = messages.conversation_id and cm.user_id = auth.uid()));

-- Realtime delivery for room and message updates.
do $$ begin
  alter publication supabase_realtime add table public.rooms;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;
